tasks:
  - name: setup and start server
    init: npm install
    command: npm run dev

  - name: install firebase-tools
    command: npm install -g firebase-tools

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
