tasks:
  - name: setup and start server
    init: npm install
    command: npm run dev

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - albert.tabout
    - amazonwebservices.aws-toolkit-vscode
